import csv
from datetime import datetime
from typing import List, Optional
from pathlib import Path
from .scraper.base import Product


class OutputFormatter:
    def __init__(self, output_dir: str = "."):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def format_timestamp(self) -> str:
        return datetime.now().strftime("%Y%m%d_%H%M%S")
    
    def to_csv(self, products: List[Product], filename: Optional[str] = None) -> str:
        if not filename:
            filename = f"product_comparison_{self.format_timestamp()}.csv"
        
        filepath = self.output_dir / filename
        
        with open(filepath, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["rank", "product_name", "price", "rating", "sales_volume", "platform", "source_url"])
            
            for i, product in enumerate(products, 1):
                writer.writerow([
                    i,
                    product.name,
                    f"{product.price:.2f}",
                    f"{product.rating:.1f}",
                    self._format_sales(product.sales_volume),
                    product.platform,
                    product.source_url,
                ])
        
        return str(filepath)
    
    def to_markdown(self, products: List[Product], search_term: str = "", filename: Optional[str] = None) -> str:
        if not filename:
            filename = f"product_comparison_{self.format_timestamp()}.md"
        
        filepath = self.output_dir / filename
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# Product Comparison Report\n\n")
            f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            if search_term:
                f.write(f"**Search Term:** {search_term}\n")
            f.write(f"**Total Products:** {len(products)}\n\n")
            
            f.write("| Rank | Product | Price | Rating | Sales | Platform |\n")
            f.write("|------|---------|-------|--------|-------|----------|\n")
            
            for i, product in enumerate(products, 1):
                stars = "⭐" * int(product.rating) if product.rating > 0 else "-"
                name = product.name or "Unknown"
                f.write(f"| {i} | {self._truncate(name, 40)} | ¥{product.price:.2f} | {stars}{product.rating:.1f} | {self._format_sales(product.sales_volume)} | {product.platform} |\n")
            
            f.write("\n---\n\n")
            f.write("*Report generated by E-commerce Procurement Research Tool*\n")
        
        return str(filepath)
    
    def _format_sales(self, sales: int) -> str:
        if sales >= 10000:
            return f"{sales // 10000}万+"
        elif sales >= 1000:
            return f"{sales // 1000}k+"
        return str(sales)
    
    def _truncate(self, text: str, max_length: int) -> str:
        if len(text) <= max_length:
            return text
        return text[:max_length - 3] + "..."
